#Jekyll 
permalink: /:title
plugins: [jekyll-paginate-v2, jekyll-sitemap]
encoding: "utf-8"

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded
exclude: ["Gemfile", "Gemfile.lock", "vendor"]

excerpt_separator: <!--e-->

pagination:
  enabled: true
  per_page: 3
  permalink: "/page=:num/"
  sort_reverse: true
  sort_field: "date"

# Uncomment and edit the below block, if you need to exclude files (pdf, etc.) from the sitemap. 
# But keep in mind a possible increase in building time.
# For editable documents (txt, etc.) you can add "sitemap: false" to the front-matter.

#defaults:
#  -
#    scope:
#      path: "/assets/**/*.*"
#    values:
#      sitemap: false

#Site
url: https://do-your-own-seo.com
lang: uk
languages: "uk ru en"
name: "Do Your Own SEO"

author:
  name: Olya Vo
  job: Technical SEO
  thumb: /images/author-avatar.jpg
  github: https://github.com/do-your-own-seo?tab=repositories
  twitter: https://twitter.com/olyavo
  email: https://contact.do/44CB

ga: UA-145849621-1
comments: true

github-repo: "do-your-own-seo/do-your-own-seo.github.io"
staticman:
    branch: "source"
    app: "https://dyos.herokuapp.com"

recaptcha:
  siteKey: "6LcrELsUAAAAABaEzQPKYAwk3YPEBQJbBlQMjnWJ"
  secret: "dD0f5GSBIfJBoqGynHs6Ovp6qatv9aGCUPnmHR/jS38QHeWfMUFhnKyPrk8qxA9BD+LS4fFnLQCHc4AEDsaFOaFHyUKRfpYx7fS0fn6MKk6ZcsXWE/7U39rBQ1ePKk9h8dWYWBLz0Ax5Ftyj0VPuRYnkvnqQupOz6igZxCV0vibNEu4RDs48fiMNDKb0QKtxy/WgcIEe89x3uUHgzmiIXS9Bk6WYLqdRrejr+Okbtdq/uSYuG1r/NHd5YHvQhyDKtOoaVygXMfR36uO5NtXAZtGWEo5QHrWn0k3Hrcxl4t4Ek3CAJ14bXmVAUhlfiHdtqP1mI0ACBdbvIVTaAoxvRw=="

# Translation
t:
  title: 
    uk: "ХендМейд SEO: все про оптимізацію сайту власними силами"
    ru: "SEO самостоятельно: оптимизируем сайт своими силами!"
    en: "SEO for everyone: read, think &amp; Do It Yourself"

  type: 
    uk: "блог"
    ru: "блог"
    en: "blog"

  keywords: 
    uk: "SEO блог"
    ru: "SEO блог"
    en: "SEO blog"

  description:
      uk: "SEO оптимізація сайту власними силами &#9728; Як зрозуміти і використовувати SEO на практиці &#9728; Як дійти згоди з Google і не боятися апдейтів пошукових систем"
      ru: "Оптимизация сайта своими силами – это реально &#9728; Как понять и применять SEO на практике &#9728; Как поладить с Google и не бояться апдейтов поисковых систем"
      en: "Symbiosis of SEO practice and theory &#9728; Website optimization on your own &#9728; Іf you understand SEO, you can Do It Yourself: it's adventurous and exciting!"
  
  pagination:
    title:
      uk: "Do Your Own SEO блог - сторінка "
      ru: "Do Your Own SEO блог - страница "
      en: "Do Your Own SEO blog - page "

  about:
    uk: "Інтро + Контакти"
    ru: "Интро + Контакты"
    en: "Intro and Contacts"

  show:
    uk: "Меню"
    ru: "Меню"
    en: "Show navbar"

  hide:
    uk: "Закрити меню"
    ru: "Свернуть меню"
    en: "Hide navbar"

  minRead:
    uk: "хв читання"
    ru: "мин чтения"
    en: "min read"

  related:
    uk: "Пов'язані публікації"
    ru: "Другие статьи по теме"
    en: "Related Posts"

  share:
    uk: "Поширити"
    ru: "Поделиться статьей"
    en: "Share the info"

  bye:
    uk: "Сподіваюся, буде цікаво"
    ru: "Надеюсь, будет интересно"
    en: "I hope you find it useful"

  commentSection:
    uk: "Коментарі"
    ru: "Комментарии"
    en: "Comments"

  comment:
    uk: "Коментар"
    ru: "Сообщение"
    en: "Message"

  commentName:
    uk: "Ім'я"
    ru: "Имя"
    en: "Name"

  commentSite:
    uk: "Ваш сайт"
    ru: "Ваш сайт"
    en: "Website"

  commentsClosed:
    uk: "Коментарі тимчасово вимкнуто"
    ru: "Комментарии отключены"
    en: "Comments are closed"

  pleaseContactMe:
    uk: "Якщо вам є що додати або виникли питання, будь ласка, "
    ru: "Если вам есть что добавить или возникли вопросы, пожалуйста, "
    en: "If you have a question concerning the content of the page, feel free to "

  pleaseContactMeAnchor:
    uk: "зв'яжіться зі мною"
    ru: "дайте мне знать"
    en: "contact me"

  submitComment:
    uk: "Надіслати"
    ru: "Отправить"
    en: "Submit"

  commentSending:
    uk: "В&nbsp;процесі..."
    ru: "Отправляю..."
    en: "Sending..."

  commentSubmitted:
    uk: "Відправлено"
    ru: "Отправлено"
    en: "Submitted"

  commentNotSubmitted:
    uk: "Відхилено"
    ru: "Отклонено"
    en: "Not&nbsp;submitted"

  commentSuccess:
    uk: "Дякую за відгук! Повідомлення з'явиться на сайті після модерації людиною :)"
    ru: "Спасибо за отзыв! Текст появится на сайте после одобрения человеком :)"
    en: "Thank you for the comment! It is currently pending but will appear once approved."

  commentReject:
    uk: ":( На жаль, щось трапилось. Будь ласка, перевірте, чи всі важливі поля заповнені коректно."
    ru: ":( К сожалению, не вышло. Пожалуйста, убедитесь, что необходимые поля заполнены корректно."
    en: "Please make sure the required fields have been completed correctly. :( Sorry for the error."

  cookieMessage:
    uk: " reCAPTCHA &ndash; це Google-сервіс, який читає cookies.\n Натискаючи Надіслати, ви погоджуєтеся з політикою Google:\n\n"
    ru: " reCAPTCHA &ndash; это Google-сервис, который читает cookies.\n Отправляя сообщение, вы соглашаетесь с политикой Google:\n\n"
    en: " reCAPTCHA reads cookies.\n By submitting a comment, you agree with Google's Privacy policy:\n\n"
  
  honeypot:
    uk: "Пастка для ботів"
    ru: "Ловушка для ботов"
    en: "If you are a human"
  
  honeypotPlacehold:
    uk: "залиште як є"
    ru: "оставить как есть"
    en: "leave as it is"

  emailPlacehold:
    uk: "для gravatar"
    ru: "для gravatar"
    en: "for gravatar only"
    
  reply:
    uk: "Відповісти"
    ru: "Ответить"
    en: "Reply"

  cancelReply:
    uk: "Скасувати відповідь"
    ru: "Отменить ответ"
    en: "Cancel reply"
  
  footnote:
    uk: "Контент – предмет авторського права, код відкритий згідно з "
    ru: "Контент – предмет авторского права, код доступен по "
    en: "Content is copyrighted; the code is  available under the "

  cat:
    uk: "Хто, я? Я і не живий-то взагалі"
    ru: "Кто, я? Я даже не живой вообще!"
    en: "Who, me? I'm not even alive!"